#!/bin/bash
branch="develop.blake"

if [ -z $1 ]
then
	branch=$branch
else
	branch=$1
fi
read -p "Enter Commit Message: " message
printf "Will commit with the following message:\n$message\n"
read -p "Push to origin.$branch?[Y/N]: " res
case $res in
	y | Y)
		echo "okay... pushing..."
		eval "git add ."
		eval "git commit -m $message"
		eval "git push origin $branch";;
	n | N) echo "okay... will not push";;
esac
